name: mytask
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.7.5
  font_awesome_flutter: ^8.8.1
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  international_phone_input: ^1.0.4
  intl_phone_number_input: ^0.4.6+2

 

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter_icons:
  android: true
  ios: true
  image_path: "assets/mytaskreal.jpg"
  adaptive_icon_background: "assets/backgroundimage.jpg"
  adaptive_icon_foreground: "assets/logo_foreground.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/mytaskreal.jpg
  #   - images/a_dot_ham.jpeg
